---
kind: pipeline
type: docker
name: build-aarch64

platform:
  arch: arm64
  os: linux

steps:
  - name: build-3.18
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO}
      tags:
        - 3.18-aarch64
      dockerfile: "3.18/Dockerfile"
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-3.19
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO}
      tags:
        - 3.19-aarch64
      dockerfile: "3.19/Dockerfile"
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-3.20
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO}
      tags:
        - 3.20-aarch64
      dockerfile: "3.20/Dockerfile"
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-3.21
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO}
      tags:
        - 3.21-aarch64
      dockerfile: "3.21/Dockerfile"
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-3.22
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO}
      tags:
        - 3.22-aarch64
        - latest-aarch64
      dockerfile: "3.22/Dockerfile"
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]

---
kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: build-3.18
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO}
      tags:
        - 3.18-amd64
      dockerfile: "3.18/Dockerfile"
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-3.19
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO}
      tags:
        - 3.19-amd64
      dockerfile: "3.19/Dockerfile"
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-3.20
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO}
      tags:
        - 3.20-amd64
      dockerfile: "3.20/Dockerfile"
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-3.21
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO}
      tags:
        - 3.21-amd64
      dockerfile: "3.21/Dockerfile"
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-3.22
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO}
      tags:
        - 3.22-amd64
        - latest-amd64
      dockerfile: "3.22/Dockerfile"
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]

---
kind: pipeline
type: docker
name: multiarch-manifest

steps:
  - name: manifest-3.18
    image: plugins/manifest
    settings:
      spec: 3.18/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-3.19
    image: plugins/manifest
    settings:
      spec: 3.19/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-3.20
    image: plugins/manifest
    settings:
      spec: 3.20/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-3.21
    image: plugins/manifest
    settings:
      spec: 3.21/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-3.22
    image: plugins/manifest
    settings:
      spec: 3.22/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: healthcheck
    image: ubuntu
    environment:
      HEALTHCHECKS_URL:
        from_secret: healthchecks_url
    commands:
      - apt-get update
      - apt-get -y install curl
      - |
        if [ ${DRONE_BUILD_STATUS} = success ]; then
          curl --retry 3 $${HEALTHCHECKS_URL}
        else
          curl --retry 3 $${HEALTHCHECKS_URL}/fail
        fi
    when:
      status: [success, failure]

depends_on: [build-aarch64, build-amd64]

---
kind: signature
hmac: 76ea1e59ab7b082b220844adb5b154429a49d46072083e178b5ed34436d87dce

...
