---
kind: pipeline
type: docker
name: build-aarch64

platform:
  arch: arm64
  os: linux

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO}
      tags:
        - ${DRONE_BRANCH}-aarch64
        - latest-aarch64
      username: andreipoe
      password:
        from_secret: docker_token

---
kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO}
      tags:
        - ${DRONE_BRANCH}-amd64
        - latest-amd64
      username: andreipoe
      password:
        from_secret: docker_token

---
kind: pipeline
type: docker
name: multiarch-manifest

steps:
  - name: manifest
    image: plugins/manifest
    settings:
      target: ${DRONE_REPO}
      spec: .drone/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token

depends_on: [build-aarch64, build-amd64]

---
kind: signature
hmac: ba8fff0c7d1e82965e616c0d5a9fe157b59f37402b80efe8ec49687125837208

...
