image: andreipoe/buildpack-alpine:{{build.branch}}
tags: [latest]

manifests:
  - image: andreipoe/buildpack-alpine:{{build.branch}}-aarch64
    platform:
      architecture: arm64
      os: linux
  - image: andreipoe/buildpack-alpine:{{build.branch}}-amd64
    platform:
      architecture: amd64
      os: linux
